### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2#113]
```
^CTraceback (most recent call last):
  File "/home/zdenal/.envs/arcor2/bin/arcor2_server", line 11, in <module>
    load_entry_point('arcor2', 'console_scripts', 'arcor2_server')()
  File "/home/zdenal/arcor2_repos/arcor2/arcor2/nodes/server.py", line 216, in main
    loop.run_until_complete(asyncio.gather(exe.project_manager_client(handle_manager_incoming_messages),
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
```

**Comment by ZdenekM** [comment]
Fixed by https://github.com/robofit/arcor2/pull/127.
