### ISSUE TITLE
websockets.exceptions.ConnectionClosed not handled everywhere

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2#129]
Occurred on branch devel, commit 458224727788e753255e268d7c669ae9b99f23cd.

```
server - INFO    : Unregistering ui
Unhandled exception; stopping loop.
Traceback (most recent call last):
  File "/home/zdenal/.envs/arcor2/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/zdenal/.envs/arcor2/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/zdenal/.envs/arcor2/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/zdenal/.envs/arcor2/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/zdenal/.envs/arcor2/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zdenal/.envs/arcor2/bin/arcor2_server", line 11, in <module>
    load_entry_point('arcor2', 'console_scripts', 'arcor2_server')()
  File "/home/zdenal/arcor2_repos/arcor2/arcor2/nodes/server.py", line 232, in main
    run(aio_main(), loop=loop, stop_on_unhandled_errors=True)
  File "/home/zdenal/.envs/arcor2/lib/python3.8/site-packages/aiorun.py", line 294, in run
    raise pending_exception_to_raise
  File "/home/zdenal/.envs/arcor2/lib/python3.8/site-packages/websockets/protocol.py", line 555, in send
    await self.ensure_open()
  File "/home/zdenal/.envs/arcor2/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by ZdenekM** [comment]
I'm not able to reproduce it so far.

**Comment by ZdenekM** [comment]
![unknown](https://user-images.githubusercontent.com/1199396/83142643-13532500-a0f1-11ea-8c1c-525f5bb52cb5.png)

**Comment by ZdenekM** [comment]
Hopefully fixed by https://github.com/robofit/arcor2/pull/130.
