### ISSUE TITLE
Failed to save/update project

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2#785]
```
fit-demo-asset                  | Name:     AssetsController.CreateAsset (Kinalisoft.Asset.WebApiControllers)                                                                                                fit-demo-asset                  | Duration: 2.205ms                                                                                                                                                          fit-demo-asset                  | Events:                                                                                                                                                                    fit-demo-asset                  |      Method Arguments [10:05:11.316124] Debug                                                                                                                              fit-demo-asset                  |         id: pro_2e99c03e10554ed68f3ed5e320aa5190                                                                                                                           fit-demo-asset                  |         type: Project                                                                                                                                                      fit-demo-asset                  |         dependencies: [scn_94db6c5dfe7040f6b027c3a9b558d937]                                                                                                               fit-demo-asset                  |         tags: []                                                                                                                                                           fit-demo-asset                  |         assetData: {FileName:fitdemo,Length:14688,ContentType:multipart/form-data}                                                                                         fit-demo-asset                  |      Exception [10:05:11.317045] Error                                                                                                                                     fit-demo-asset                  |         Message: Asset exist on path fitdemo.                                                                                                                              fit-demo-asset                  |         Type: System.ArgumentException                                                                                                                                     fit-demo-asset                  |         StackTrace:    at Kinalisoft.Asset.Web.StorageAssetSystemFixed.CreateAsset(String id, String filePath, String description, String type, String[] dependencies, Byte[] assetData, String[] tags) in /src/Kinalisoft.Asset.Web/StorageAssetSystemFixed.cs:line 78                                                                                                                 fit-demo-asset                  |    at Kinalisoft.Asset.WebApiControllers.AssetsController.CreateAsset(String id, String directoryPath, String description, String type, String[] dependencies, String[] tags, IFormFile assetData) in /src/Kinalisoft.Asset.WebApiControllers/AssetsController.cs:line 89                                                                                                               fit-demo-asset                  |    at lambda_method22(Closure , Object , Object[] )                                                                                                                        
fit-demo-asset                  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object c
ontroller, Object[] arguments)                                                                        
fit-demo-asset                  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
fit-demo-asset                  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)                                 fit-demo-asset                  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
fit-demo-asset                  | --- End of stack trace from previous location ---                                                                                                                          fit-demo-asset                  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
fit-demo-asset                  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)                                 fit-demo-asset                  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
fit-demo-asset                  | --- End of stack trace from previous location ---                                                                                                                          fit-demo-asset                  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope sco
pe, Object state, Boolean isCompleted)                                                                                                                                                                       fit-demo-asset                  | 
fit-demo-project                | Time:     2022-09-14T10:05:11.285122               
fit-demo-project                | Name:     ProjectsController.ProjectPut (Kinalisoft.Project.WebApi.Controllers)                                                                                            fit-demo-project                | Duration: 33.257ms
...
fit-demo-project                |      Exception [10:05:11.318261] Error
fit-demo-project                |         Message: Asset exist on path fitdemo.
fit-demo-project                |         Type: System.ArgumentException
fit-demo-project                |         StackTrace:    at Kinalisoft.Asset.Web.WebAssetExtensions.HandleException(HttpResponseMessage response, HttpClient client) in /home/gitlab-runner/builds/yihxx8wA/0/test-it-off/asset/asset/Kinalisoft.Asset.Web/WebAssetExtensions.cs:line 74
fit-demo-project                |    at Kinalisoft.Asset.Web.WebAssetExtensions.HandleResult(Task`1 task, HttpClient client) in /home/gitlab-runner/builds/yihxx8wA/0/test-it-off/asset/asset/Kinalisoft.Asset.Web/WebAssetExtensions.cs:line 52
fit-demo-project                |    at Kinalisoft.Asset.Web.WebAssetSystem.CreateAsset(String id, String filePath, String description, String type, String[] dependencies, Byte[] assetData, String[] tags) in /home/gitlab-runner/builds/yihxx8wA/0/test-it-off/asset/asset/Kinalisoft.Asset.Web/WebAssetSystem.cs:line 121
fit-demo-project                |    at Kinalisoft.Core.Assets.TypedAssetSystem.CreateAsset[T](String id, String filePath, T dataObject, String description, String[] tags) in /home/pickmaster/builds/kcSPsv8A/0/common-net/core/Kinalisoft.Core/Assets/TypedAssetSystem.cs:line 174
fit-demo-project                |    at Kinalisoft.Project.WebApi.Extensions.AssetSystemExtensions.PutObject[T](TypedAssetSystem assets, T item) in /src/Kinalisoft.Project.WebApi/Extensions/AssetSystemExtensions.cs:line 56
fit-demo-project                |    at lambda_method31(Closure , Object , Object[] )
fit-demo-project                |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
fit-demo-project                |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
fit-demo-project                |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
fit-demo-project                |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
fit-demo-project                | --- End of stack trace from previous location ---
fit-demo-project                |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
fit-demo-project                |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
fit-demo-project                |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
fit-demo-project                |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
fit-demo-project                | 
fit-demo-arserver               | 2022-09-14 10:05:11 ERROR    Failed to add or update the project. Kinalisoft.Project.WebApi (Argument): Asset exist on path fitdemo.
```

**Comment by ZdenekM** [comment]
...happens when the project has the same name as the scene.

**Comment by ZdenekM** [comment]
The issue is in Asset service.
